/**
 * MEDDICCScoringHandler Tests
  *
   * Jest test coverage for the MEDDICC scoring handler and stage gate validation.
    *
     * Test scenarios:
      * 1. All elements scored at maximum (5) — composite should be 100
       * 2. All elements scored at minimum (1) — composite should be 20
        * 3. Partial scoring (only some elements populated) — composite reflects weighted partial score
         * 4. No scores populated — composite should be 0
          * 5. Score change detection
           * 6. Stage gate: advancing to Solution Alignment without required scores should fail
            * 7. Stage gate: advancing to Negotiation below 65 composite should fail
             * 8. Stage gate: advancing to Negotiation with valid scores should succeed
              */

              const {
                calculateCompositeScore,
                  scoreFieldChanged,
                    validateStageGate,
                      WEIGHT_MAP,
                      } = require('../meddiccScoringHandler');

                      // ─── Helpers ──────────────────────────────────────────────────────────────

                      function buildDealProperties(overrides = {}) {
                        return {
                            meddicc_metrics_score: null,
                                meddicc_economic_buyer_score: null,
                                    meddicc_decision_criteria_score: null,
                                        meddicc_decision_process_score: null,
                                            meddicc_identified_pain_score: null,
                                                meddicc_champion_score: null,
                                                    meddicc_competition_score: null,
                                                        ...overrides,
                                                          };
                                                          }

                                                          function setAllScores(value) {
                                                            return buildDealProperties({
                                                                meddicc_metrics_score: String(value),
                                                                    meddicc_economic_buyer_score: String(value),
                                                                        meddicc_decision_criteria_score: String(value),
                                                                            meddicc_decision_process_score: String(value),
                                                                                meddicc_identified_pain_score: String(value),
                                                                                    meddicc_champion_score: String(value),
                                                                                        meddicc_competition_score: String(value),
                                                                                          });
                                                                                          }

                                                                                          // ─── Scoring Tests ────────────────────────────────────────────────────────

                                                                                          describe('calculateCompositeScore', () => {
                                                                                            test('all elements scored 5 should produce a composite of 100', () => {
                                                                                                const props = setAllScores(5);
                                                                                                    expect(calculateCompositeScore(props)).toBe(100);
                                                                                                      });
                                                                                                      
                                                                                                        test('all elements scored 1 should produce a composite of 20', () => {
                                                                                                            const props = setAllScores(1);
                                                                                                                expect(calculateCompositeScore(props)).toBe(20);
                                                                                                                  });
                                                                                                                  
                                                                                                                    test('partial scoring reflects weighted sum of populated elements only', () => {
                                                                                                                        // Only Metrics (15%) and Champion (20%) scored at 5
                                                                                                                            // Contribution: (5*15 + 5*20) / 5 = 35
                                                                                                                                const props = buildDealProperties({
                                                                                                                                      meddicc_metrics_score: '5',
                                                                                                                                            meddicc_champion_score: '5',
                                                                                                                                                });
                                                                                                                                                    expect(calculateCompositeScore(props)).toBe(35);
                                                                                                                                                      });
                                                                                                                                                      
                                                                                                                                                        test('no scores populated should produce a composite of 0', () => {
                                                                                                                                                            const props = buildDealProperties();
                                                                                                                                                                expect(calculateCompositeScore(props)).toBe(0);
                                                                                                                                                                  });
                                                                                                                                                                  
                                                                                                                                                                    test('mixed scores calculate correctly', () => {
                                                                                                                                                                        // Metrics 3*15=45, Champion 5*20=100 => (45+100)/5 = 29
                                                                                                                                                                            const props = buildDealProperties({
                                                                                                                                                                                  meddicc_metrics_score: '3',
                                                                                                                                                                                        meddicc_champion_score: '5',
                                                                                                                                                                                            });
                                                                                                                                                                                                expect(calculateCompositeScore(props)).toBe(29);
                                                                                                                                                                                                  });
                                                                                                                                                                                                  
                                                                                                                                                                                                    test('ignores invalid score values', () => {
                                                                                                                                                                                                        const props = buildDealProperties({
                                                                                                                                                                                                              meddicc_metrics_score: 'abc',
                                                                                                                                                                                                                    meddicc_champion_score: '5',
                                                                                                                                                                                                                        });
                                                                                                                                                                                                                            // Only Champion 5*20=100, (100)/5 = 20
                                                                                                                                                                                                                                expect(calculateCompositeScore(props)).toBe(20);
                                                                                                                                                                                                                                  });
                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                    test('ignores out-of-range score values', () => {
                                                                                                                                                                                                                                        const props = buildDealProperties({
                                                                                                                                                                                                                                              meddicc_metrics_score: '0',
                                                                                                                                                                                                                                                    meddicc_champion_score: '6',
                                                                                                                                                                                                                                                          meddicc_competition_score: '3',
                                                                                                                                                                                                                                                              });
                                                                                                                                                                                                                                                                  // Only Competition 3*6=18, (18)/5 = 3.6
                                                                                                                                                                                                                                                                      expect(calculateCompositeScore(props)).toBe(3.6);
                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                        // ─── Change Detection Tests ───────────────────────────────────────────────
                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                        describe('scoreFieldChanged', () => {
                                                                                                                                                                                                                                                                          test('returns true when previousProperties is null', () => {
                                                                                                                                                                                                                                                                              const current = setAllScores(3);
                                                                                                                                                                                                                                                                                  expect(scoreFieldChanged(current, null)).toBe(true);
                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                      test('returns false when no score fields changed', () => {
                                                                                                                                                                                                                                                                                          const props = setAllScores(3);
                                                                                                                                                                                                                                                                                              expect(scoreFieldChanged(props, props)).toBe(false);
                                                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                  test('returns true when a score field changed', () => {
                                                                                                                                                                                                                                                                                                      const current = setAllScores(3);
                                                                                                                                                                                                                                                                                                          const previous = { ...setAllScores(3), meddicc_champion_score: '2' };
                                                                                                                                                                                                                                                                                                              expect(scoreFieldChanged(current, previous)).toBe(true);
                                                                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                // ─── Stage Gate Tests ─────────────────────────────────────────────────────
                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                describe('validateStageGate', () => {
                                                                                                                                                                                                                                                                                                                  test('blocks Solution Alignment without Metrics score', () => {
                                                                                                                                                                                                                                                                                                                      const props = buildDealProperties({
                                                                                                                                                                                                                                                                                                                            meddicc_identified_pain_score: '3',
                                                                                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                                                                                    const result = validateStageGate('solutionalignment', props, 0);
                                                                                                                                                                                                                                                                                                                                        expect(result.allowed).toBe(false);
                                                                                                                                                                                                                                                                                                                                            expect(result.message).toContain('Metrics');
                                                                                                                                                                                                                                                                                                                                              });
                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                test('blocks Solution Alignment without Identified Pain score', () => {
                                                                                                                                                                                                                                                                                                                                                    const props = buildDealProperties({
                                                                                                                                                                                                                                                                                                                                                          meddicc_metrics_score: '3',
                                                                                                                                                                                                                                                                                                                                                              });
                                                                                                                                                                                                                                                                                                                                                                  const result = validateStageGate('solutionalignment', props, 0);
                                                                                                                                                                                                                                                                                                                                                                      expect(result.allowed).toBe(false);
                                                                                                                                                                                                                                                                                                                                                                          expect(result.message).toContain('Identified Pain');
                                                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                              test('allows Solution Alignment with both required scores', () => {
                                                                                                                                                                                                                                                                                                                                                                                  const props = buildDealProperties({
                                                                                                                                                                                                                                                                                                                                                                                        meddicc_metrics_score: '3',
                                                                                                                                                                                                                                                                                                                                                                                              meddicc_identified_pain_score: '3',
                                                                                                                                                                                                                                                                                                                                                                                                  });
                                                                                                                                                                                                                                                                                                                                                                                                      const result = validateStageGate('solutionalignment', props, 18);
                                                                                                                                                                                                                                                                                                                                                                                                          expect(result.allowed).toBe(true);
                                                                                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                              test('blocks Negotiation when not all scores populated', () => {
                                                                                                                                                                                                                                                                                                                                                                                                                  const props = buildDealProperties({
                                                                                                                                                                                                                                                                                                                                                                                                                        meddicc_metrics_score: '4',
                                                                                                                                                                                                                                                                                                                                                                                                                              meddicc_champion_score: '4',
                                                                                                                                                                                                                                                                                                                                                                                                                                  });
                                                                                                                                                                                                                                                                                                                                                                                                                                      const result = validateStageGate('negotiationreview', props, 56);
                                                                                                                                                                                                                                                                                                                                                                                                                                          expect(result.allowed).toBe(false);
                                                                                                                                                                                                                                                                                                                                                                                                                                              expect(result.message).toContain('All 7');
                                                                                                                                                                                                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                  test('blocks Negotiation when composite score below 65', () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                      const props = setAllScores(2); // composite = 40
                                                                                                                                                                                                                                                                                                                                                                                                                                                          const result = validateStageGate('negotiationreview', props, 40);
                                                                                                                                                                                                                                                                                                                                                                                                                                                              expect(result.allowed).toBe(false);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  expect(result.message).toContain('65');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      test('allows Negotiation when all scores populated and composite >= 65', () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const props = setAllScores(4); // composite = 80
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const result = validateStageGate('negotiationreview', props, 80);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  expect(result.allowed).toBe(true);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      test('allows any other stage without restriction', () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const props = buildDealProperties();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const result = validateStageGate('prospecting', props, 0);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  expect(result.allowed).toBe(true);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });
